name: Publish CocoaPods

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Publish cocoapods
      run: pod trunk push SwiftExtensionChimaera.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
